server:
  port: 8080

stats-server:
  url: "http://localhost:8080"

spring:
  main:
    banner-mode: off

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration